version: "3"
services:
  backend:
    container_name: liwm1_backend
    image: "m1adow/liwm1:${LIWM1_VERSION}"
    ports:
      - 5240:80
    env_file:
      - backend.env
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: liwm1_postgres
    image: 'postgres:16.1'
    ports:
      - '5432:5432'
    env_file:
      - postgres.env
    volumes:
      - 'liwm1_postgres_db:/var/lib/postgresql/data'
    restart: always
