version: "3.8"
services:
  liwm1_backend:
    container_name: liwm1_backend
    image: "m1adow/liwm1:${LIWM1_VERSION}"
    build:
      context: ../../
      dockerfile: ./webAPI/Dockerfile
    ports:
      - 5240:80
    env_file:
      - .env
    depends_on:
      - liwm1_postgres
    restart: always

  liwm1_postgres:
    container_name: liwm1_postgres
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    volumes:
      - liwm1_postgres_db:/var/lib/postgresql/data
    restart: always
volumes:
  liwm1_postgres_db: